services:
  ts-rsync:
    image: tailscale/tailscale:stable
    container_name: ts-rsync
    hostname: apple-ts-backup
    env_file: "./secrets/apple.env"
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts-rsync-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  rsync-server:
    image: eeacms/rsync:3.0
    container_name: rsync-server
    command: server
    env_file: "./secrets/ssh-auth-key.env"
    volumes:
      - "/mnt/backup/:/data/"
    network_mode: service:ts-rsync
    restart: unless-stopped
    depends_on:
      - ts-rsync

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_HOSTNAME=apple
      - DOZZLE_NO_ANALYTICS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    network_mode: service:ts-dozzle
    depends_on:
      -  ts-dozzle

  ts-dozzle:
    image: tailscale/tailscale:stable
    container_name: ts-dozzle
    hostname: apple-ts-dozzle
    env_file: "./secrets/tailscale.env"
    environment:
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ts-dozzle-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

volumes:
  ts-rsync-state:
    name: "apple-ts-rsync-state"
  ts-dozzle-state:
    name: "apple-ts-dozzle-state"
